# Generated by Django 4.2.3 on 2023-07-11 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_lookbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='lookbook',
            name='items',
            field=models.CharField(default='a chair', max_length=200),
        ),
    ]
