# Generated by Django 4.2.3 on 2023-07-11 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_lookbook_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lookbook',
            name='items',
        ),
    ]
