# Generated by Django 4.2.3 on 2023-07-11 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_lookbook_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='lookbook',
            name='items',
            field=models.TextField(default='Default', max_length=500),
        ),
    ]
