# Generated by Django 4.2.3 on 2023-07-12 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shoppinglist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('products', models.ManyToManyField(to='main_app.product')),
            ],
        ),
    ]
